[package]
name = "dlpc8445_flasher_gui"
version = "0.3.0"
authors = ["Stefan Kerkmann <karlk90@pm.me>"]
edition = "2024"

[dependencies]
dioxus = { version = "0.7.1", features = [] }
dioxus-icons = { version = "0.1.0", default-features = false }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
git-version = "0.3.9"

# web
[target.'cfg(target_family = "wasm")'.dependencies]
webusb-web = "0.5.1"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
